package redactedrice.randomizer.context;

import org.junit.jupiter.api.Test;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for EnumDefinition class.
 * Tests the core enum definition functionality and expansion behavior.
 */
public class EnumDefinitionTest {

    @Test
    public void testBasicEnumDefinition() {
        List<String> values = Arrays.asList("RED", "GREEN", "BLUE");
        Map<String, Integer> valueMap = new LinkedHashMap<>();
        valueMap.put("RED", 0);
        valueMap.put("GREEN", 1);
        valueMap.put("BLUE", 2);

        EnumDefinition def = new EnumDefinition("Color", values, valueMap, null);

        assertEquals("Color", def.getName());
        assertEquals(3, def.getValues().size());
        assertTrue(def.hasValue("RED"));
        assertTrue(def.hasValue("GREEN"));
        assertTrue(def.hasValue("BLUE"));
        assertEquals(0, def.getValue("RED").intValue());
        assertEquals(1, def.getValue("GREEN").intValue());
        assertEquals(2, def.getValue("BLUE").intValue());
    }

    @Test
    public void testCaseInsensitiveValueCheck() {
        EnumDefinition def = new EnumDefinition("Test",
                Arrays.asList("VALUE1", "VALUE2"),
                Map.of("VALUE1", 0, "VALUE2", 1),
                null);

        assertTrue(def.hasValue("VALUE1"));
        assertTrue(def.hasValue("value1"));
        assertTrue(def.hasValue("Value1"));
    }

    @Test
    public void testExpandWithNewValues() {
        // Create original enum
        Map<String, Integer> initialValueMap = new LinkedHashMap<>();
        initialValueMap.put("WARRIOR", 0);
        initialValueMap.put("MAGE", 1);
        initialValueMap.put("ROGUE", 2);
        EnumDefinition original = new EnumDefinition("EntityType",
                Arrays.asList("WARRIOR", "MAGE", "ROGUE"),
                initialValueMap,
                null);

        // Expand with new values
        Map<String, Integer> newValueMap = new LinkedHashMap<>();
        newValueMap.put("PALADIN", 100);
        newValueMap.put("NECROMANCER", 101);
        EnumDefinition expanded = original.expandWith(Arrays.asList("PALADIN", "NECROMANCER"),
                newValueMap);

        // Verify original is unchanged (immutability)
        assertEquals(3, original.getValues().size());
        assertFalse(original.hasValue("PALADIN"));

        // Verify expanded has all values
        assertEquals(5, expanded.getValues().size());
        assertTrue(expanded.hasValue("WARRIOR"));
        assertTrue(expanded.hasValue("MAGE"));
        assertTrue(expanded.hasValue("ROGUE"));
        assertTrue(expanded.hasValue("PALADIN"));
        assertTrue(expanded.hasValue("NECROMANCER"));

        // Verify value mappings
        assertEquals(0, expanded.getValue("WARRIOR").intValue());
        assertEquals(1, expanded.getValue("MAGE").intValue());
        assertEquals(2, expanded.getValue("ROGUE").intValue());
        assertEquals(100, expanded.getValue("PALADIN").intValue());
        assertEquals(101, expanded.getValue("NECROMANCER").intValue());

        // Verify order is preserved
        assertEquals(Arrays.asList("WARRIOR", "MAGE", "ROGUE", "PALADIN", "NECROMANCER"),
                expanded.getValues());
    }

    @Test
    public void testExpandWithDuplicatesIgnored() {
        EnumDefinition original = new EnumDefinition("Test",
                Arrays.asList("A", "B", "C"),
                Map.of("A", 0, "B", 1, "C", 2),
                null);

        // Try to add duplicate values
        EnumDefinition expanded = original.expandWith(Arrays.asList("B", "D"), Map.of("D", 3));

        // Should have 4 values (A, B, C, D) - duplicate B is skipped
        assertEquals(4, expanded.getValues().size());
        assertEquals(Arrays.asList("A", "B", "C", "D"), expanded.getValues());
        
        // Original B value should be unchanged
        assertEquals(1, expanded.getValue("B").intValue());
        assertEquals(3, expanded.getValue("D").intValue());
    }

    @Test
    public void testExpandWithAutoGeneratedValues() {
        EnumDefinition original = new EnumDefinition("Test",
                Arrays.asList("A", "B"),
                Map.of("A", 0, "B", 1),
                null);

        // Add new values without explicit mappings
        EnumDefinition expanded = original.expandWith(Arrays.asList("C", "D"), null);

        // Should auto-generate values starting from max + 1
        assertEquals(4, expanded.getValues().size());
        assertEquals(0, expanded.getValue("A").intValue());
        assertEquals(1, expanded.getValue("B").intValue());
        assertEquals(2, expanded.getValue("C").intValue()); // Auto-generated
        assertEquals(3, expanded.getValue("D").intValue()); // Auto-generated
    }

    @Test
    public void testExpandWithEmptyListReturnsUnchanged() {
        EnumDefinition original = new EnumDefinition("Test",
                Arrays.asList("A", "B"),
                Map.of("A", 0, "B", 1),
                null);

        EnumDefinition expanded = original.expandWith(Collections.emptyList(), null);

        // Should return the same instance since nothing changed
        assertSame(original, expanded);
    }

    @Test
    public void testExpandWithNullListReturnsUnchanged() {
        EnumDefinition original = new EnumDefinition("Test",
                Arrays.asList("A", "B"),
                Map.of("A", 0, "B", 1),
                null);

        EnumDefinition expanded = original.expandWith(null, null);

        // Should return the same instance since nothing changed
        assertSame(original, expanded);
    }

    @Test
    public void testExpandWithMixedExplicitAndAutoValues() {
        EnumDefinition original = new EnumDefinition("Test",
                Arrays.asList("A", "B"),
                Map.of("A", 5, "B", 10),
                null);

        // Add C with explicit value, D without
        Map<String, Integer> newValues = new LinkedHashMap<>();
        newValues.put("C", 20);
        EnumDefinition expanded = original.expandWith(Arrays.asList("C", "D"), newValues);

        assertEquals(5, expanded.getValue("A").intValue());
        assertEquals(10, expanded.getValue("B").intValue());
        assertEquals(20, expanded.getValue("C").intValue()); // Explicit
        assertEquals(21, expanded.getValue("D").intValue()); // Auto-generated from max(20) + 1
    }

    // Note: EnumDefinition doesn't make defensive copies of the values list
    // All callers in EnumRegistry create new ArrayLists, so this isn't an issue in practice

    @Test
    public void testImmutabilityOfReturnedValuesList() {
        EnumDefinition def = new EnumDefinition("Test",
                Arrays.asList("A", "B"),
                Map.of("A", 0, "B", 1),
                null);

        List<String> values = def.getValues();

        // Trying to modify returned list should throw exception
        assertThrows(UnsupportedOperationException.class, () -> values.add("C"));
    }

    @Test
    public void testEnumClassPreservedAfterExpansion() {
        enum TestEnum { VALUE1, VALUE2 }

        EnumDefinition original = new EnumDefinition("TestEnum",
                Arrays.asList("VALUE1", "VALUE2"),
                Map.of("VALUE1", 0, "VALUE2", 1),
                TestEnum.class);

        EnumDefinition expanded = original.expandWith(Arrays.asList("VALUE3"), Map.of("VALUE3", 2));

        // Enum class reference should be preserved
        assertEquals(TestEnum.class, expanded.getEnumClass());
    }
}
